#!/bin/bash
set -euo pipefail
wid=$(docker ps --latest --filter "name=${XSCANPY_CONTAINER_NAME}" --format="{{.ID}}")
if [[ -z $wid ]]; then
    exit 1
fi
docker kill $wid > /dev/null 2>&1 || :
docker rm $wid
